name: Publish the package to Github Package Registry
on:
  release:
    types: [created]
permissions:
  packages: write
jobs:
  github-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Set up Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: .nvmrc
          registry-url: 'https://npm.pkg.github.com'
          always-auth: true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install dependencies and build with builder bob
        run: yarn install --frozen-lockfile
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@172994372753cb896adac383df48b1d7a2dae4d1 # v3.23
      - name: Publish Package
        run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
