name: Publish the package npm registry
on:
  release:
    types: [created]
jobs:
  npm:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      - name: Setup Node
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5
        with:
          node-version-file: .nvmrc
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies and build with builder bob
        run: yarn install --frozen-lockfile
      - name: Publish package on NPM 📦
        run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_RELEASE_TOKEN }}
